/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;
import javax.swing.JOptionPane;
import java.io.*;
import tda.lista.generica.ListaG;
import Clases_Bibliotecas.Bibliotecario;
import Clases_Bibliotecas.Libros;
import Clases_Bibliotecas.Alumno;
/**
 *
 * @author Marco Alejandro
 */
public class FormBiblioteca extends javax.swing.JFrame {
    ListaG<Bibliotecario> L1; //Bibiiotecario
    ListaG<Libros> L2; //Libros
    ListaG<Alumno> L3; //Alumno
    /**
     * Creates new form FormBiblioteca
     */
    public FormBiblioteca() {
        //Cualquier cosa que hagas aqui
        //Se ejecuta al crear el formulario
        initComponents();
        cargarBibliotecarios();
        cargarLibros();
        cargarAlumnos();
        /*L2=new ListaG<Alumnos>();
        while (!filaEs->vacio()){
            Alumno A1=new Alumno();
            L2.insertar(A1);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setLabel("Cargar Bibliotecario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(17, 22, 134, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Source Code Pro", 3, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 20, 830, 209);

        jButton2.setLabel("Cargar Libro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(17, 57, 95, 23);

        jButton3.setLabel("Cargar Alumno");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(17, 92, 111, 23);

        jButton4.setLabel("Mostrar Bibliotecarios");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(17, 127, 145, 23);

        jButton5.setLabel("Mostrar Libros");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(17, 162, 106, 23);

        jButton6.setLabel("Mostrar Alumnos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(20, 200, 122, 23);

        jButton7.setLabel("Buscar Bibliotecario");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(20, 230, 134, 23);

        jButton8.setLabel("Buscar Libro");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(20, 260, 95, 23);

        jButton9.setLabel("Buscar Alumno");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(20, 290, 111, 23);

        jButton10.setText("jButton10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(150, 260, 81, 20);

        jButton11.setText("jButton11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(270, 260, 81, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarBibliotecarios() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("bibliotecario.dat"))) {
            L1 = (ListaG<Bibliotecario>) ois.readObject();
        } catch (IOException | ClassNotFoundException e) {
            L1 = new ListaG<Bibliotecario>(); // si no hay archivo aún, iniciar vacío
        }
    }
    
    private void cargarLibros() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("libro.dat"))) {
            L2 = (ListaG<Libros>) ois.readObject();
        } catch (IOException | ClassNotFoundException e) {
            L2 = new ListaG<Libros>(); // si no hay archivo aún, iniciar vacío
        }
    }
    
    private void cargarAlumnos() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("alumno.dat"))) {
            L3 = (ListaG<Alumno>) ois.readObject();
        } catch (IOException | ClassNotFoundException e) {
            L3 = new ListaG<Alumno>(); // si no hay archivo aún, iniciar vacío
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Pedir datos al usuario
        String codStr = JOptionPane.showInputDialog(null, "Ingrese el código:","0");
        int Cod = Integer.parseInt(codStr);

        String ciStr = JOptionPane.showInputDialog(null, "Ingrese el CI:","0");
        int CI = Integer.parseInt(ciStr);

        String Nombre = JOptionPane.showInputDialog(null, "Ingrese el Nombre:");

        String sexoStr = JOptionPane.showInputDialog(null, "Ingrese el Sexo (M O F):"," ");
        char Sexo = sexoStr.charAt(0);
  
        Bibliotecario B1=new Bibliotecario(Cod,CI,Nombre,Sexo);
        if (B1.getNom()!=null && B1.getNom()!="") {
            
            L1.insertar(B1); //L1 es los bibliotecarios
            if (L1.Buscar(B1)) {
                L1.Modificar(B1, B1);
            }
        
            // GUARDAR lista L1 en archivo "bibliotecario.dat"
           try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("bibliotecario.dat"))) {
               oos.writeObject(L1); // ← Guarda el objeto completo ListaG<Bibliotecario>
               JOptionPane.showMessageDialog(this, "Guardado en bibliotecario.dat");
           } catch (IOException e) {
               JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
           }
        }else{
            JOptionPane.showMessageDialog(this, "Error al guardar debido a no colocar bien los datos ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // Pedir datos al usuario
        String codStr = JOptionPane.showInputDialog(null, "Ingrese el código:","0");
        int Cod = Integer.parseInt(codStr);

        String Nombre = JOptionPane.showInputDialog(null, "Ingrese el Nombre:");

        String Autor = JOptionPane.showInputDialog(null, "Ingrese el Autor:");
        
        String Categoria = JOptionPane.showInputDialog(null, "Ingrese el Categoria:");
        
        String StoStr = JOptionPane.showInputDialog(null, "Ingrese el Stock:","0");
        int Stock = Integer.parseInt(StoStr);
        
        Libros Li1 = new Libros(Cod,Nombre,Autor,Categoria,Stock);

        if (Li1.getNombre()!=null && Li1.getNombre()!="") {
            
            L2.insertar(Li1); //L2 es la ListaG de Libros
            
            // GUARDAR lista L2 en archivo "libro.dat"
           try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("libro.dat"))) {
               oos.writeObject(L2); // ← Guarda el objeto completo ListaG<>
               JOptionPane.showMessageDialog(this, "Guardado en libro.dat");
           } catch (IOException e) {
               JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
           }
        }else{
            JOptionPane.showMessageDialog(this, "Error al guardar debido a no colocar bien los datos ");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int i;
        Libros Laux;
        String Cod = JOptionPane.showInputDialog(null, "Ingrese el Codigo del Libro:");
        int codi = Integer.parseInt(Cod);
        Laux = new Libros(codi,"","","",0);
        if (L2.Buscar(Laux)) {
            jTextArea1.setText(L2.BuscarObj(Laux).toString());
        }else{
            jTextArea1.setText("NO EXISTE EL LIBRO");
        }   
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(L1.toString());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String RegStr = JOptionPane.showInputDialog(null, "Ingrese el Registro del Estudiante:","0");
        int Reg = Integer.parseInt(RegStr);

        String ciStr = JOptionPane.showInputDialog(null, "Ingrese el CI:","0");
        int CI = Integer.parseInt(ciStr);

        String Nombre = JOptionPane.showInputDialog(null, "Ingrese el Nombre:");

        String sexoStr = JOptionPane.showInputDialog(null, "Ingrese el Sexo (M O F):"," ");
        char Sexo = sexoStr.charAt(0);
        
        String EdaStr = JOptionPane.showInputDialog(null, "Ingrese la Edad:","0");
        int Edad = Integer.parseInt(EdaStr);
        
        String TeleStr = JOptionPane.showInputDialog(null, "Ingrese el Telefono:","0");
        int Telefono = Integer.parseInt(TeleStr);
        
        String Carrera = JOptionPane.showInputDialog(null, "Ingrese la Carrera:");

        
        Alumno A1 = new Alumno(Reg,CI,Nombre,Sexo,Edad,Telefono,Carrera);
        if (A1.getNombre()!=null && A1.getNombre()!="") {
            
            L3.insertar(A1); //L3 es la lista de Alumnos
            
            // GUARDAR lista L3 en archivo "alumno.dat"
           try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("alumno.dat"))) {
               oos.writeObject(L3); // ← Guarda el objeto completo ListaG<>
               JOptionPane.showMessageDialog(this, "Guardado en alumno.dat");
           } catch (IOException e) {
               JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
           }
        }else{
            JOptionPane.showMessageDialog(this, "Error al guardar debido a no colocar bien los datos ");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(L2.toString());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(L3.toString());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int i;
        Alumno Laux;
        String Cod = JOptionPane.showInputDialog(null, "Ingrese el Registro del Alumno:");
        int codi = Integer.parseInt(Cod);
        for (i = 1; i <= L3.cantidad(); i++) {
            Laux=L3.GetDato(i);
            if (Laux.getRegistro()==codi) {
                jTextArea1.setText(Laux.toString());
                return;
            }
        }
        jTextArea1.setText("NO EXISTE EL ALUMNO");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int i;
        Bibliotecario Laux;
        String Cod = JOptionPane.showInputDialog(null, "Ingrese el Codigo del Bibliotecario:");
        int codi = Integer.parseInt(Cod);
        for (i = 1; i <= L1.cantidad(); i++) {
            Laux=L1.GetDato(i);
            if (Laux.getCod()==codi) {
                jTextArea1.setText(Laux.toString());
                return;
            }
        }
        jTextArea1.setText("NO EXISTE EL BIBLIOTECARIO");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int i;
        Libros Laux;
        String Cat = JOptionPane.showInputDialog(null, "Ingrese el Nombre del Libro");
        jTextArea1.setText("");
        for (i = 1; i <= L2.cantidad(); i++) {
            Laux=L2.GetDato(i);
            String S=Cat.toUpperCase();
            System.out.println(S);
            if (Laux.getCategoria().toUpperCase().equals(S)) { //CON STRINGS NO SE PUEDE USAR EL == SE USA EL .equal
                jTextArea1.setText(jTextArea1.getText()+Laux.getNombre()+"\n"+Laux.getAutor()+"\n"+"\n");
            }
        }
        if (!(jTextArea1.getText().equals(""))) {
            return;
        }
        jTextArea1.setText("NO EXISTE EL LIBRO");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String codStr = JOptionPane.showInputDialog(null, "Ingrese el código:","0");
        int Cod = Integer.parseInt(codStr);

        Bibliotecario B1=new Bibliotecario(Cod,3,"df",'M');    
        L1.Eliminar(B1);

           try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("bibliotecario.dat"))) {
               oos.writeObject(L1); // ← Guarda el objeto completo ListaG<Bibliotecario>
               JOptionPane.showMessageDialog(this, "Guardado en bibliotecario.dat");
           } catch (IOException e) {
               JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
           }    

                
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBiblioteca().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
